[platformio]
default_envs = atmega644pa

[env:atmega644pa]
platform = atmelavr@^5.1.0
board = ATmega644P
board_build.f_cpu = 11059200L
upload_protocol = usbasp
build_flags =
    -std=gnu11
    -Wall
    -Wextra
    -Werror
