[platformio]
default_envs = atmega644pa

[env:atmega644pa]
platform = atmelavr@^5.1.0
board = ATmega644P
board_build.f_cpu = 11059200L
upload_protocol = usbasp
# PlatformIO adds -D to AVR uploads.  An explicit erase is required for ISP
# uploads because flash programming alone cannot change a bit from 0 back to 1.
upload_flags =
    -e
build_flags =
    -std=gnu11
    -Wall
    -Wextra
    -Werror
